server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: iaiotecp-backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smartclassroom.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl